wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: resnet
depth:
  desc: null
  value: 101
dataset:
  desc: null
  value: NIPS4Bplus
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700769710.189266
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
